repos:
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    -   id: black
        args: [--safe]
        language_version: python3.7
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.5.0
    hooks:
    -   id: seed-isort-config
        args: [--application-directories, "."]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
        additional_dependencies: ["flake8-bugbear == 18.8.0"]
        language_version: python3.7
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.11.3
    hooks:
    -   id: pyupgrade
